---
title: "Get Wind Cave NP data"
author: "Max Joseph"
date: "December 20, 2018"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r, message=FALSE}
library(geoknife)
library(geojsonio)
library(leaflet)
library(rgdal)
library(tidyverse)
library(raster)
```

Get national park service boundaries. 

```{r}
geojson_path <- 'nps.geojson'
if (!file.exists(geojson_path)) {
  url <- 'http://open-fedmaps.opendata.arcgis.com/datasets/8b98df1300b749eabc3142864bb9a119_0.geojson'
  download.file(url, destfile = geojson_path)
}

parks <- geojson_read(geojson_path, what = "sp")
poly <- subset(parks, UNIT_NAME == "Wind Cave National Park") %>%
  spTransform("+proj=longlat +datum=WGS84")
```

Plot a map of subset boundaries. 

```{r}
leaflet(poly) %>%
  addTiles() %>%
  addPolygons()
```

## Get climate data

First generate a table of which models and variables we want.

```{r}
vars <- c('pr', 'tasmax')
models <- c('BNU-ESM_r1i1p1', 'CNRM-CM5_r1i1p1', 
            'CSIRO-Mk3-6-0_r1i1p1', 'CanESM2_r1i1p1', 'GFDL-ESM2G_r1i1p1', 
            'GFDL-ESM2M_r1i1p1', 'HadGEM2-CC365_r1i1p1', 'HadGEM2-ES365_r1i1p1', 
            'IPSL-CM5A-LR_r1i1p1', 'IPSL-CM5A-MR_r1i1p1', 'IPSL-CM5B-LR_r1i1p1', 
            'MIROC-ESM-CHEM_r1i1p1', 'MIROC-ESM_r1i1p1', 'MIROC5_r1i1p1', 
            'MRI-CGCM3_r1i1p1', 'bcc-csm1-1-m_r1i1p1', 'bcc-csm1-1_r1i1p1')

climate_vars <- expand.grid(vars = vars, 
                            models = models, 
                            rcp = c('rcp45', 'rcp85')) %>%
  as_tibble %>%
  mutate(var_name = paste(vars, models, rcp, sep = "_"))

climate_vars
```

Then use geoknife to extract the data.

```{r}
get_maca <- function(poly, time, vars, period) {
  stopifnot(period %in% c('future', 'historical'))
  stencil <- simplegeom(poly)
  fabric <- webdata(
    list(
      times = time,
      url = paste0('http://cida.usgs.gov/thredds/dodsC/macav2metdata_monthly_', 
                   period),
      variables = vars$var_name))
  job <- geoknife(stencil, fabric, wait = TRUE)
  Sys.sleep(90)
  parks_climate <- result(job, with.units = TRUE)
  parks_climate
}
```

```{r}
times <- list(
  c('2006-01-01', '2015-12-01'), 
  c('2016-01-01', '2025-12-01'), 
  c('2026-01-01', '2035-12-01'), 
  c('2036-01-01', '2046-01-01'))
out <- list()
for (i in seq_along(times)) {
  out[[i]] <- get_maca(poly, time = times[[i]], 
                       vars = climate_vars, period = 'future')
}
```


Combine output into one tibble

```{r}
future_climate <- out %>%
  bind_rows %>%
  distinct %>%
  as_tibble %>%
  gather(park, value, -DateTime, -variable, -statistic, -units) %>%
  dplyr::select(-park) %>%
  separate(variable, c('var', 'model', 'run', 'scenario'), 
         sep = '_', remove = FALSE)
#write_csv(future_climate, 'future_climate.csv')
```

